### ISSUE TITLE
Plot the accuracy vs the params graph for the learning rate

### ISSUE THREAD

**Issue by DantrazTrev** [DantrazTrev/Neural-Networks#6]

**Comment by exoushia** [comment]
working on issue #6

I was debugging the code and trying to run the test database, and i ran into this error:
Traceback (most recent call last):
  File "test.py", line 25, in <module>
    net.SGD(training_data, 30, 10, 3.0, test_data=test_data)
  File "/home/mitushi/Desktop/kwoc/Neural-Networks/network.py", line 35, in SGD
    self.update_mini_batch(mini_batch, eta)
  File "/home/mitushi/Desktop/kwoc/Neural-Networks/network.py", line 45, in update_mini_batch
    delta_nabla_b, delta_nabla_w,net = backprop(self,x, y)
  File "/home/mitushi/Desktop/kwoc/Neural-Networks/backpropogation.py", line 17, in backprop
    delta = net.cost_derivative(activations[-1], y) * \
  File "/home/mitushi/Desktop/kwoc/Neural-Networks/network.py", line 59, in cost_derivative
    return (output_activations-y)
ValueError: operands could not be broadcast together with shapes (30,1) (10,1) 

I guess there's a mismatch between the expected output shape and the shape of the database. How should i fix this?

**Comment by DantrazTrev** [comment]
I think the issue was in the way we were handling the network update in the `backpropogation.py`. I've tried to fix it, the issue was not intentional, you can check there is still an issue up which is unlisted

**Comment by DantrazTrev** [comment]
@exoushia I guess that issue has been solved now.

**Comment by aryancoolvats** [comment]
# hi i am ayush pratap singh and I pretend to be a beautiful girl from norway but in reality i'm just some dude.                 
![poop](https://pbs.twimg.com/media/DKkIAP5U8AA1XrU.jpg "this is who I pretend to be")           
i have a norwegian flag on my profile even though i am nowhere even related to it.        
![poopy](https://i.imgur.com/OBJkpd4.png "eats poop")           
on my instagram page i come up with laughably terrible posts like this one                                  
![lolswtfisthisshit](https://i.imgur.com/ly67sb0.png "haha what a retardd")
